export const LAB_COPY = {
  en: {
    eyebrow: "Off-duty experiments / Vol. 01",
    title: ["PLAY IS", "THE POINT."],
    intro:
      "A little curiosity. A little chaos. Six small experiments with absolutely no productive purpose.",
    invitation: "Go on. Touch something.",
    collection: "Choose your distraction",
    live: "LIVE",
    paused: "PAUSED",
    pause: "Pause",
    resume: "Resume",
    reset: "Reset",
    next: "Next experiment",
    back: "Back to the real world",
    footer: "Built for the joy of figuring things out.",
    controls: "Your controls",
    keyboard: "Keyboard: focus the canvas, use arrow keys to move, Space to interact.",
    reduced: "Motion starts paused. Press Resume when you’re ready.",
    unavailable: "This browser cannot display the experiment. Try a browser with Canvas support.",
    best: "Personal best",
    score: "Locks",
    ready: "Ready when you are.",
    start: "Start a run",
    lock: "Lock it in",
    again: "Try again",
    hit: "Locked. Keep going.",
    perfect: "Dead centre. Beautiful.",
    miss: "Just missed. One more go?",
    gameHint:
      "Catch the white needle inside the red zone. Each lock gets a little faster. One miss ends the run.",
    formLabel: "Particle form",
    forms: ["Monogram", "Infinity", "Knot"],
    physics: {
      spring: { label: "Spring", low: "Soft", high: "Firm" },
      damping: { label: "Damping", low: "Bouncy", high: "Settled" },
    },
    bricks: "Bricks",
    won: "All clear. Nicely done.",
    breakerHint:
      "Move the paddle with your pointer or arrow keys. Clear all 32 bricks. Keep the ball alive.",
    playing: "Keep it alive.",
    drawKeyboard: "Keyboard: Space toggles drawing. Arrow keys move the brush.",
    grabKeyboard: "Keyboard: Space grabs or releases. Arrow keys move your hand.",
    wordLabel: "Your word",
    stamp: "Stamp it ↓",
    experiments: [
      {
        id: "orbit",
        name: "Strange attractor",
        category: "01 / PARTICLE PLAYGROUND",
        description:
          "From a thousand possibilities, a single form. Follow the flow, stir it gently, and watch it find its way back.",
        instruction: "Move to stir · click to ripple",
        action: "Transform the form",
        parameter: "Flow",
        low: "Slow",
        high: "Lively",
        hint: "Choose a shape. Trace its edges. Every particle has somewhere to return to.",
      },
      {
        id: "chrome",
        name: "Liquid chrome",
        category: "02 / MATERIAL STUDY",
        description:
          "Heavy metal. Soft edges. Pull a silver droplet out of the pool and watch it melt back into the whole.",
        instruction: "Drag to stretch · release to melt",
        action: "Split the mercury",
        parameter: "Viscosity",
        low: "Liquid",
        high: "Syrupy",
        hint: "Grab a droplet and pull it away. Stir the surface, split the pool, or just enjoy the reflections.",
      },
      {
        id: "lock",
        name: "One more orbit",
        category: "03 / TIMING GAME",
        description: "One button. A moving target. An unreasonable urge to beat your last score.",
        instruction: "Click or press Space to lock",
        action: "Start a run",
        parameter: "",
        low: "",
        high: "",
        hint: "Your best run stays on this device. How far can you take it?",
      },
      {
        id: "foundry",
        name: "Type foundry",
        category: "04 / TYPE PLAYGROUND",
        description:
          "Words with a little weight behind them. Stamp your own, grab a letter, and make a beautiful mess.",
        instruction: "Grab a letter · drag and release to throw",
        action: "Shake things up",
        parameter: "Gravity",
        low: "Moon",
        high: "Heavy",
        hint: "Stamp another word. Stack the letters, throw them around, or turn gravity down and let them drift.",
      },
      {
        id: "mirror",
        name: "Mirror ink",
        category: "05 / SYMMETRY STUDIO",
        description:
          "One small gesture, a whole new pattern. Turn a wandering line into something worth staring at.",
        instruction: "Drag to draw · make your mark",
        action: "Clear the canvas",
        parameter: "Symmetry",
        low: "3 folds",
        high: "12 folds",
        hint: "Hold and draw. Every stroke is mirrored around the centre. Change the symmetry and layer another.",
      },
      {
        id: "breaker",
        name: "Signal breaker",
        category: "06 / MICRO ARCADE",
        description:
          "An old-school obsession in a new coat of paint. One ball. Thirty-two bricks. You know what to do.",
        instruction: "Move to steer · click to launch",
        action: "Launch the ball",
        parameter: "",
        low: "",
        high: "",
        hint: "Hit with the edge of the paddle to change the angle. Your best score stays on this device.",
      },
    ],
  },
  pl: {
    eyebrow: "Eksperymenty po godzinach / Vol. 01",
    title: ["CZAS NA", "ZABAWĘ."],
    intro:
      "Trochę ciekawości. Trochę chaosu. Sześć małych eksperymentów bez żadnego produktywnego celu.",
    invitation: "Śmiało. Dotknij czegoś.",
    collection: "Wybierz swoją rozrywkę",
    live: "AKTYWNY",
    paused: "PAUZA",
    pause: "Pauza",
    resume: "Wznów",
    reset: "Od nowa",
    next: "Następny eksperyment",
    back: "Powrót do rzeczywistości",
    footer: "Z czystej radości odkrywania.",
    controls: "Sterowanie",
    keyboard: "Klawiatura: wybierz płótno, poruszaj się strzałkami, użyj Spacji, aby zadziałać.",
    reduced: "Animacja jest wstrzymana. Wybierz Wznów, kiedy zechcesz.",
    unavailable:
      "Ta przeglądarka nie obsługuje eksperymentu. Spróbuj przeglądarki z obsługą Canvas.",
    best: "Twój rekord",
    score: "Trafienia",
    ready: "Zacznij, kiedy zechcesz.",
    start: "Rozpocznij grę",
    lock: "Złap sygnał",
    again: "Jeszcze raz",
    hit: "Trafiony. Tak trzymaj.",
    perfect: "Idealnie w środek. Pięknie.",
    miss: "O włos. Jeszcze raz?",
    gameHint:
      "Zatrzymaj białą wskazówkę w czerwonej strefie. Każde trafienie przyspiesza grę. Jeden błąd kończy rundę.",
    formLabel: "Forma cząstek",
    forms: ["Monogram", "Nieskończoność", "Węzeł"],
    physics: {
      spring: { label: "Sprężystość", low: "Miękko", high: "Sztywno" },
      damping: { label: "Tłumienie", low: "Sprężyście", high: "Spokojnie" },
    },
    bricks: "Klocki",
    won: "Wszystko rozbite. Pięknie.",
    breakerHint:
      "Steruj paletką ruchem lub strzałkami. Rozbij wszystkie 32 klocki. Nie zgub piłki.",
    playing: "Nie zgub piłki.",
    drawKeyboard: "Klawiatura: Spacja włącza i wyłącza rysowanie. Strzałki poruszają pędzlem.",
    grabKeyboard: "Klawiatura: Spacja chwyta lub puszcza. Strzałki poruszają dłonią.",
    wordLabel: "Twoje słowo",
    stamp: "Odbij je ↓",
    experiments: [
      {
        id: "orbit",
        name: "Dziwny atraktor",
        category: "01 / PLAC ZABAW CZĄSTEK",
        description:
          "Z tysiąca możliwości powstaje jedna forma. Podążaj za ruchem, delikatnie go zaburz i obserwuj powrót.",
        instruction: "Ruch porusza · kliknięcie faluje",
        action: "Zmień formę",
        parameter: "Przepływ",
        low: "Powoli",
        high: "Żwawo",
        hint: "Wybierz kształt. Podążaj po jego krawędziach. Każda cząstka ma dokąd wrócić.",
      },
      {
        id: "chrome",
        name: "Płynny chrom",
        category: "02 / STUDIUM MATERIAŁU",
        description:
          "Ciężki metal. Miękkie krawędzie. Wyciągnij srebrną kroplę z kałuży i obserwuj, jak wtapia się z powrotem.",
        instruction: "Przeciągnij, żeby rozciągnąć · puść, żeby scalić",
        action: "Rozdziel krople",
        parameter: "Lepkość",
        low: "Płynnie",
        high: "Gęsto",
        hint: "Chwyć kroplę i odciągnij ją. Zamieszaj powierzchnię, rozdziel kałużę albo po prostu podziwiaj odbicia.",
      },
      {
        id: "lock",
        name: "Jeszcze jedna orbita",
        category: "03 / GRA NA WYCZUCIE",
        description: "Jeden przycisk. Ruchomy cel. I nieodparta ochota, żeby pobić swój wynik.",
        instruction: "Kliknij lub naciśnij Spację",
        action: "Rozpocznij grę",
        parameter: "",
        low: "",
        high: "",
        hint: "Twój rekord zostaje na tym urządzeniu. Jak daleko zajdziesz?",
      },
      {
        id: "foundry",
        name: "Odlewnia liter",
        category: "04 / ZABAWA TYPOGRAFIĄ",
        description:
          "Słowa, które mają swój ciężar. Odbij własne, chwyć literę i zrób piękny bałagan.",
        instruction: "Chwyć literę · przeciągnij i puść, żeby rzucić",
        action: "Potrząśnij literami",
        parameter: "Grawitacja",
        low: "Księżyc",
        high: "Ciężko",
        hint: "Odbij kolejne słowo. Układaj litery, rzucaj nimi albo zmniejsz grawitację i pozwól im dryfować.",
      },
      {
        id: "mirror",
        name: "Lustrzany tusz",
        category: "05 / STUDIO SYMETRII",
        description:
          "Mały gest, zupełnie nowy wzór. Zmień błądzącą linię w coś, od czego trudno oderwać wzrok.",
        instruction: "Przeciągnij, żeby rysować",
        action: "Wyczyść płótno",
        parameter: "Symetria",
        low: "3 odbicia",
        high: "12 odbić",
        hint: "Przytrzymaj i rysuj. Każdy ruch odbija się wokół środka. Zmień symetrię i dodaj kolejną warstwę.",
      },
      {
        id: "breaker",
        name: "Rozbij sygnał",
        category: "06 / MIKRO ARCADE",
        description:
          "Klasyczna obsesja w nowej oprawie. Jedna piłka. Trzydzieści dwa klocki. Wiesz, co robić.",
        instruction: "Ruch steruje · kliknięcie startuje",
        action: "Wystrzel piłkę",
        parameter: "",
        low: "",
        high: "",
        hint: "Odbij krawędzią paletki, żeby zmienić kąt. Twój rekord zostaje na tym urządzeniu.",
      },
    ],
  },
} as const;

export type ExperimentKind = "orbit" | "chrome" | "lock" | "foundry" | "mirror" | "breaker";
