export const CONNECT_COPY = {
  en: {
    label: "An open door",
    title: "Human friendly,",
    accent: "agent ready.",
    lead: "Come say hello. Or let your agent make the introduction. Same person, same work, a few more ways to connect.",
    human: "For humans",
    humanTitle: "Let’s work together.",
    humanLead: "A place on your team, an extra pair of hands, or a project of your own.",
    kinds: { contract: "Contract", "full-time": "Full-time", freelance: "Freelance" },
    kindLabel: "Type of opportunity",
    draft: "Draft an email",
    emailNote: "Opens your email app with a brief to fill in. You review and send it.",
    agent: "For agents",
    agentTitle: "A little context goes a long way.",
    agentLead:
      "Experience, project evidence, and how to get in touch. Plain files your agent can read without navigating the interface.",
    resources: [
      "Experience, skills, projects & contact",
      "How to prepare a relevant inquiry",
      "A short index of the available context",
    ],
    promptLabel: "Bring your agent",
    promptTitle: "Start with this introduction.",
    promptLead:
      "Choose an opportunity above, then copy this brief into your agent. It can read the profile, assess the fit, and help write your email.",
    copy: "Copy agent brief",
    copied: "Brief copied",
    copyFailed: "Copy unavailable. Select and copy the brief below.",
    briefLabel: "Agent brief (English)",
    access: "Public context",
    format: "JSON + Markdown",
    permission: "No account needed",
    homeLink: "Meet the agent side",
    homeLead:
      "Your agent can read my profile, explore my work, and help you put an introduction into words.",
    back: "Back to the portfolio",
  },
  pl: {
    label: "Otwarte drzwi",
    title: "Dla ludzi.",
    accent: "Dla agentów też.",
    lead: "Napisz do mnie. Albo pozwól swojemu agentowi pomóc w pierwszym kontakcie. Ta sama osoba, te same projekty, kilka sposobów na rozmowę.",
    human: "Dla ludzi",
    humanTitle: "Zróbmy coś razem.",
    humanLead: "Miejsce w zespole, dodatkowa para rąk albo Twój własny projekt.",
    kinds: { contract: "Kontrakt", "full-time": "Etat", freelance: "Freelance" },
    kindLabel: "Forma współpracy",
    draft: "Przygotuj e-mail",
    emailNote: "Otwiera program pocztowy ze szkicem do uzupełnienia. Ty sprawdzasz i wysyłasz.",
    agent: "Dla agentów",
    agentTitle: "Dobry kontekst na początek.",
    agentLead:
      "Doświadczenie, zrealizowane projekty i kontakt. Proste pliki, które agent odczyta bez poruszania się po interfejsie.",
    resources: [
      "Doświadczenie, technologie, projekty i kontakt",
      "Jak przygotować zapytanie o współpracę",
      "Krótki indeks dostępnego kontekstu",
    ],
    promptLabel: "Zaproś swojego agenta",
    promptTitle: "Zacznij od przedstawienia się.",
    promptLead:
      "Wybierz formę współpracy powyżej i skopiuj tę instrukcję do agenta. Może przeczytać profil, ocenić dopasowanie i pomóc napisać e-mail.",
    copy: "Kopiuj instrukcję",
    copied: "Instrukcja skopiowana",
    copyFailed: "Kopiowanie niedostępne. Zaznacz i skopiuj instrukcję poniżej.",
    briefLabel: "Instrukcja dla agenta (po angielsku)",
    access: "Publiczny kontekst",
    format: "JSON + Markdown",
    permission: "Bez zakładania konta",
    homeLink: "Przejdź do sekcji dla agentów",
    homeLead:
      "Twój agent może przeczytać mój profil, poznać projekty i pomóc napisać pierwszą wiadomość.",
    back: "Wróć do portfolio",
  },
};
